name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # Trigger every time you commit to main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Gatsby Build
        run: npm run build:ipfs # Uses your new IPFS script
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB3_SOCIAL_CONNECT }}'
          projectId: web3-social-connect
          channelId: live
